# Generated by Django 4.2.7 on 2023-11-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categoriaproduto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaProduto',
        ),
    ]
