# Generated by Django 4.2.7 on 2023-11-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_produtovenda_venda_produtovenda_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='total',
        ),
    ]
