# Generated by Django 4.2.7 on 2023-11-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_venda_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtovenda',
            name='subtotal',
        ),
    ]
