# Generated by Django 4.2.7 on 2023-11-30 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_produtovenda_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtovenda',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='subtotal',
        ),
    ]
